# Generated by Django 3.2.3 on 2021-07-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_orders_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.AddField(
            model_name='orders',
            name='phone2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
