# Generated by Django 3.2.3 on 2021-07-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='timestamp2',
            field=models.TimeField(default=''),
        ),
    ]
