# Generated by Django 3.2.3 on 2021-07-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_orderupdate_timestamp2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='timestamp2',
        ),
    ]
